### ISSUE TITLE
Encryption of POSTGRES_URL affects traceability of the project

### ISSUE THREAD

**Issue by h1alexbel** [eyakauleva/lawoffice#12]
[Here](https://github.com/eyakauleva/lawoffice/blob/master/src/infra/pg-secrets.yaml) you encrypt ```POSTGRES_URL```.
No need to encrypt whole URL, much better will be if you will take value of ```DB_HOST``` from configmap.
Like ```PG_HOST```, while url:``` jdbc:postgresql://${PG_HOST}:5432/postgres```
Traceability and maintainability of the project will be increased.
@eyakauleva  please fix.

**Comment by eyakauleva** [comment]
[Fixed](https://github.com/eyakauleva/lawoffice/pull/13)

**Comment by h1alexbel** [comment]
@eyakauleva thanks
